services:
  - type: web
    name: PiroAutoFilterBot
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    runtime: python3
    build:
      pythonVersion: 3.10.8
    repo: https://github/ritheshrkrm/PiroAutoFilterBot.git
    region: oregon
    plan: free
    branch: master
    numInstances: 1
    healthCheckPath: /
